/*
SQLyog Ultimate v11.25 (64 bit)
MySQL - 5.5.54 : Database - farmework
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`farmework` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `farmework`;

/*Table structure for table `sys_approven_function` */

DROP TABLE IF EXISTS `sys_approven_function`;

CREATE TABLE `sys_approven_function` (
  `APPROVEN_FUNCTION_ID` varchar(10) NOT NULL COMMENT '审批功能主键',
  `APPROVEN_FUNCTION_NAME` varchar(100) NOT NULL COMMENT '审批功能名称',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT 'Y' COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  PRIMARY KEY (`APPROVEN_FUNCTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `sys_approven_function` */

insert  into `sys_approven_function`(`APPROVEN_FUNCTION_ID`,`APPROVEN_FUNCTION_NAME`,`REMARK`,`STATUS`,`CREATE_TIME`,`CREATE_USER_ID`,`CREATE_USER_NAME`,`CREATE_TEAM_ID`,`CREATE_TEAM_NAME`,`CREATE_DEPART_ID`,`CREATE_DEPART_NAME`,`CREATE_UNIT_ID`,`CREATE_UNIT_NAME`,`LAST_UPDATE_TIME`,`LAST_UPDATE_USER_ID`,`LAST_UPDATE_USER_NAME`,`LAST_UPDATE_TEAM_ID`,`LAST_UPDATE_TEAM_NAME`,`LAST_UPDATE_DEPART_ID`,`LAST_UPDATE_DEPART_NAME`,`LAST_UPDATE_UNIT_ID`,`LAST_UPDATE_UNIT_NAME`) values ('00001','请假',NULL,'Y','2017-02-16 14:54:07','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*Table structure for table `sys_approven_function_rule` */

DROP TABLE IF EXISTS `sys_approven_function_rule`;

CREATE TABLE `sys_approven_function_rule` (
  `APPROVEN_RULE_ID` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '审批规则编号',
  `APPROVEN_RULE_NAME` varchar(100) NOT NULL COMMENT '审批规则名称',
  `APPROVEN_FUNCTION_ID` varchar(10) NOT NULL COMMENT '审批功能主键',
  `APPROVEN_FUNCTION_NAME` varchar(100) NOT NULL COMMENT '审批功能名称',
  `APPROVEN_REMARK` varchar(100) DEFAULT NULL COMMENT '审批功能描述',
  `APPROVEN_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '审批班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `APPROVEN_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '审批班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `APPROVEN_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '审批科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `APPROVEN_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '审批科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `APPROVEN_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '审批单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `APPROVEN_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '审批单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `RULE_IS_ORDERLY` varchar(10) NOT NULL COMMENT '师傅按序审批(1：有序审批、2、无序审批)',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT 'Y' COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  PRIMARY KEY (`APPROVEN_RULE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

/*Data for the table `sys_approven_function_rule` */

insert  into `sys_approven_function_rule`(`APPROVEN_RULE_ID`,`APPROVEN_RULE_NAME`,`APPROVEN_FUNCTION_ID`,`APPROVEN_FUNCTION_NAME`,`APPROVEN_REMARK`,`APPROVEN_TEAM_ID`,`APPROVEN_TEAM_NAME`,`APPROVEN_DEPART_ID`,`APPROVEN_DEPART_NAME`,`APPROVEN_UNIT_ID`,`APPROVEN_UNIT_NAME`,`RULE_IS_ORDERLY`,`REMARK`,`STATUS`,`CREATE_TIME`,`CREATE_USER_ID`,`CREATE_USER_NAME`,`CREATE_TEAM_ID`,`CREATE_TEAM_NAME`,`CREATE_DEPART_ID`,`CREATE_DEPART_NAME`,`CREATE_UNIT_ID`,`CREATE_UNIT_NAME`,`LAST_UPDATE_TIME`,`LAST_UPDATE_USER_ID`,`LAST_UPDATE_USER_NAME`,`LAST_UPDATE_TEAM_ID`,`LAST_UPDATE_TEAM_NAME`,`LAST_UPDATE_DEPART_ID`,`LAST_UPDATE_DEPART_NAME`,`LAST_UPDATE_UNIT_ID`,`LAST_UPDATE_UNIT_NAME`) values (0000000001,'公司请假','00001','请假','测试','','','','','001001001','十达科技','1',NULL,'Y','2017-02-16 15:12:02','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*Table structure for table `sys_approven_rule_person` */

DROP TABLE IF EXISTS `sys_approven_rule_person`;

CREATE TABLE `sys_approven_rule_person` (
  `approven_person_id` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '审批规则编号',
  `APPROVEN_RULE_ID` varchar(10) NOT NULL COMMENT '审批规则编号',
  `APPROVEN_RULE_NAME` varchar(100) NOT NULL COMMENT '审批规则名称',
  `APPROVEN_FUNCTION_ID` varchar(10) NOT NULL COMMENT '审批功能主键',
  `APPROVEN_FUNCTION_NAME` varchar(100) NOT NULL COMMENT '审批功能名称',
  `approven_user_id` varchar(100) NOT NULL COMMENT '审批人编号(SYS_USER_INFO.USER_ID)',
  `approven_user_name` varchar(100) NOT NULL COMMENT '审批人姓名(SYS_USER_INFO.USER_NAME)',
  `approven_team_id` varchar(100) DEFAULT NULL COMMENT '审批人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `approven_team_name` varchar(100) DEFAULT NULL COMMENT '审批人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `approven_depart_id` varchar(100) DEFAULT NULL COMMENT '审批人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `approven_depart_name` varchar(100) DEFAULT NULL COMMENT '审批人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `approven_unit_id` varchar(100) NOT NULL COMMENT '审批人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `approven_unit_name` varchar(100) NOT NULL COMMENT '审批人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `rule_order` varchar(100) NOT NULL COMMENT '审批顺序',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT NULL COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  PRIMARY KEY (`approven_person_id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

/*Data for the table `sys_approven_rule_person` */

insert  into `sys_approven_rule_person`(`approven_person_id`,`APPROVEN_RULE_ID`,`APPROVEN_RULE_NAME`,`APPROVEN_FUNCTION_ID`,`APPROVEN_FUNCTION_NAME`,`approven_user_id`,`approven_user_name`,`approven_team_id`,`approven_team_name`,`approven_depart_id`,`approven_depart_name`,`approven_unit_id`,`approven_unit_name`,`rule_order`,`REMARK`,`STATUS`,`CREATE_TIME`,`CREATE_USER_ID`,`CREATE_USER_NAME`,`CREATE_TEAM_ID`,`CREATE_TEAM_NAME`,`CREATE_DEPART_ID`,`CREATE_DEPART_NAME`,`CREATE_UNIT_ID`,`CREATE_UNIT_NAME`,`LAST_UPDATE_TIME`,`LAST_UPDATE_USER_ID`,`LAST_UPDATE_USER_NAME`,`LAST_UPDATE_TEAM_ID`,`LAST_UPDATE_TEAM_NAME`,`LAST_UPDATE_DEPART_ID`,`LAST_UPDATE_DEPART_NAME`,`LAST_UPDATE_UNIT_ID`,`LAST_UPDATE_UNIT_NAME`) values (0000000016,'0000000001','公司请假','00001','请假','1','系统管理员','','','','','001','集团','1',NULL,NULL,'2017-02-16 17:37:34','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*Table structure for table `sys_approven_task` */

DROP TABLE IF EXISTS `sys_approven_task`;

CREATE TABLE `sys_approven_task` (
  `TASK_ID` varchar(10) NOT NULL COMMENT '任务编号',
  `TASK_NAME` varchar(10) NOT NULL COMMENT '任务名称',
  `APPROVEN_PERSON_ID` varchar(100) NOT NULL COMMENT '审批人规则id（sys_approven_rule.approven_rule_id）',
  `APPROVEN_RULE_ID` varchar(10) NOT NULL COMMENT '规则id（sys_approven_rule.approven_rule_id）',
  `APPROVEN_RULE_NAME` varchar(100) NOT NULL COMMENT '规则名称（sys_approven_rule.approven_rule_name）',
  `APPROVEN_FUNCTION_ID` varchar(10) NOT NULL COMMENT '审批功能编号（sys_approven_function.approven_function_id）',
  `APPROVEN_FUNCTION_NAME` varchar(100) NOT NULL COMMENT '审批功能名称（sys_approven_function.approven_function_name）',
  `approven_user_id` varchar(100) NOT NULL COMMENT '审批人编号(SYS_USER_INFO.USER_ID)',
  `approven_user_name` varchar(100) NOT NULL COMMENT '审批人姓名(SYS_USER_INFO.USER_NAME)',
  `RULE_ORDER` int(100) NOT NULL COMMENT '审批人顺序',
  `APPROVEN_SEND_TIME` datetime DEFAULT NULL COMMENT '审批发起时间',
  `APPROVEN_END_TIME` datetime DEFAULT NULL COMMENT '审批完成时间',
  `APPROVEN_STATUS` varchar(100) NOT NULL COMMENT '当前状态（1：未审批、2已审批）',
  `SOURCE_TABLE` varchar(100) NOT NULL COMMENT '数据来源表名称(具体业务表名)',
  `SOURCE_TABLE_PK_COLUMN_NAME` varchar(100) NOT NULL COMMENT '数据来源表主键列名称(具体业务表名.主键)',
  `SOURCE_TABLE_PK_COLUMN_VALUE` varchar(100) NOT NULL COMMENT '数据来源表主键列对应数据(具体业务表名.主键对应数据)',
  `APPROVEN_REMARK` varchar(100) NOT NULL COMMENT '审批意见',
  `RULE_ORDER_OLD` int(100) NOT NULL COMMENT '原始序号',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT 'Y' COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  PRIMARY KEY (`TASK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `sys_approven_task` */

/*Table structure for table `sys_approven_tasked` */

DROP TABLE IF EXISTS `sys_approven_tasked`;

CREATE TABLE `sys_approven_tasked` (
  `TASK_ID` varchar(10) NOT NULL COMMENT '任务编号',
  `TASK_NAME` varchar(10) NOT NULL COMMENT '任务名称',
  `APPROVEN_PERSON_ID` varchar(100) NOT NULL COMMENT '审批人规则id（sys_approven_rule.approven_rule_id）',
  `APPROVEN_RULE_ID` varchar(10) NOT NULL COMMENT '规则id（sys_approven_rule.approven_rule_id）',
  `APPROVEN_RULE_NAME` varchar(100) NOT NULL COMMENT '规则名称（sys_approven_rule.approven_rule_name）',
  `APPROVEN_FUNCTION_ID` varchar(10) NOT NULL COMMENT '审批功能编号（sys_approven_function.approven_function_id）',
  `APPROVEN_FUNCTION_NAME` varchar(100) NOT NULL COMMENT '审批功能名称（sys_approven_function.approven_function_name）',
  `approven_user_id` varchar(100) NOT NULL COMMENT '审批人编号(SYS_USER_INFO.USER_ID)',
  `approven_user_name` varchar(100) NOT NULL COMMENT '审批人姓名(SYS_USER_INFO.USER_NAME)',
  `RULE_ORDER` varchar(100) NOT NULL COMMENT '审批人顺序',
  `APPROVEN_SEND_TIME` datetime DEFAULT NULL COMMENT '审批发起时间',
  `APPROVEN_END_TIME` datetime DEFAULT NULL COMMENT '审批完成时间',
  `APPROVEN_STATUS` varchar(100) NOT NULL COMMENT '当前状态（1：未审批、2已审批）',
  `SOURCE_TABLE` varchar(100) NOT NULL COMMENT '数据来源表名称(具体业务表名)',
  `SOURCE_TABLE_PK_COLUMN_NAME` varchar(100) NOT NULL COMMENT '数据来源表主键列名称(具体业务表名.主键)',
  `SOURCE_TABLE_PK_COLUMN_VALUE` varchar(100) NOT NULL COMMENT '数据来源表主键列对应数据(具体业务表名.主键对应数据)',
  `APPROVEN_REMARK` varchar(100) NOT NULL COMMENT '审批意见',
  `RULE_ORDER_OLD` varchar(100) NOT NULL COMMENT '原始序号',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT 'Y' COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  PRIMARY KEY (`TASK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `sys_approven_tasked` */

/*Table structure for table `sys_depart_info` */

DROP TABLE IF EXISTS `sys_depart_info`;

CREATE TABLE `sys_depart_info` (
  `DEPART_ID` varchar(100) NOT NULL COMMENT '主键',
  `DEPART_NAME` varchar(10) NOT NULL COMMENT '组织名称',
  `DEPART_DESC` varchar(100) NOT NULL COMMENT '组织描述',
  `UNIT_ID` varchar(10) NOT NULL COMMENT '单位编号',
  `UNIT_NAME` varchar(100) NOT NULL COMMENT '单位名称',
  `PARENT_DEPART_ID` varchar(100) NOT NULL COMMENT '父节点id',
  `FUNCTION_SEQUE` int(11) NOT NULL COMMENT '顺序',
  `IS_VIRTUAL` varchar(100) NOT NULL COMMENT '是否虚节点（0：虚节点，1：实节点）',
  `NODE_TYPE` varchar(100) NOT NULL COMMENT '(0：根节点、1：单位、2：部门、3：科室、4：班组、5：角色)',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT 'Y' COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  PRIMARY KEY (`DEPART_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `sys_depart_info` */

insert  into `sys_depart_info`(`DEPART_ID`,`DEPART_NAME`,`DEPART_DESC`,`UNIT_ID`,`UNIT_NAME`,`PARENT_DEPART_ID`,`FUNCTION_SEQUE`,`IS_VIRTUAL`,`NODE_TYPE`,`REMARK`,`STATUS`,`CREATE_TIME`,`CREATE_USER_ID`,`CREATE_USER_NAME`,`CREATE_TEAM_ID`,`CREATE_TEAM_NAME`,`CREATE_DEPART_ID`,`CREATE_DEPART_NAME`,`CREATE_UNIT_ID`,`CREATE_UNIT_NAME`,`LAST_UPDATE_TIME`,`LAST_UPDATE_USER_ID`,`LAST_UPDATE_USER_NAME`,`LAST_UPDATE_TEAM_ID`,`LAST_UPDATE_TEAM_NAME`,`LAST_UPDATE_DEPART_ID`,`LAST_UPDATE_DEPART_NAME`,`LAST_UPDATE_UNIT_ID`,`LAST_UPDATE_UNIT_NAME`) values ('001','十达集团','十达集团','001','十达集团','-1',1,'1','0',NULL,'Y','2017-02-16 13:47:57','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('001001','单位','单位','001','十达集团','001',1,'0','1',NULL,'Y','2017-02-16 13:47:57','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('001001001','十达科技','十达科技','001001001','十达科技','001001',1,'1','1',NULL,'Y','2017-02-16 14:05:21','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('001001001001','部门','部门','001001001','十达科技','001001001',1,'0','2',NULL,'Y','2017-02-16 14:05:21','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('001001001002','角色','角色','001001001','十达科技','001001001',1,'0','5',NULL,'Y','2017-02-16 14:05:21','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('001001001002001','系统管理员','角色','001001001','十达科技','001001001002',1,'0','5',NULL,'Y','2017-02-16 14:26:51','0000000001','系统管理员','','','','','001','集团','2017-02-16 14:43:06','0000000001','系统管理员','','','','','001','集团');

/*Table structure for table `sys_dictionary_info` */

DROP TABLE IF EXISTS `sys_dictionary_info`;

CREATE TABLE `sys_dictionary_info` (
  `DICTIONARY_ID` varchar(10) NOT NULL COMMENT '字典主键',
  `DICTIONARY_NAME` varchar(10) NOT NULL COMMENT '字典名称',
  `DICTIONARY_DESC` varchar(100) NOT NULL COMMENT '字典内容描述',
  `DICTIONARY_TYPE_ID` varchar(10) NOT NULL COMMENT '字典内容类型(SYS_DICTIONARY_INFO.DICTIONARY_YTPE_ID)',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT 'Y' COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  PRIMARY KEY (`DICTIONARY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `sys_dictionary_info` */

insert  into `sys_dictionary_info`(`DICTIONARY_ID`,`DICTIONARY_NAME`,`DICTIONARY_DESC`,`DICTIONARY_TYPE_ID`,`REMARK`,`STATUS`,`CREATE_TIME`,`CREATE_USER_ID`,`CREATE_USER_NAME`,`CREATE_TEAM_ID`,`CREATE_TEAM_NAME`,`CREATE_DEPART_ID`,`CREATE_DEPART_NAME`,`CREATE_UNIT_ID`,`CREATE_UNIT_NAME`,`LAST_UPDATE_TIME`,`LAST_UPDATE_USER_ID`,`LAST_UPDATE_USER_NAME`,`LAST_UPDATE_TEAM_ID`,`LAST_UPDATE_TEAM_NAME`,`LAST_UPDATE_DEPART_ID`,`LAST_UPDATE_DEPART_NAME`,`LAST_UPDATE_UNIT_ID`,`LAST_UPDATE_UNIT_NAME`) values ('000010001','查询','查询','00001',NULL,'Y','2017-02-16 10:54:32','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('000010002','修改','修改','00001',NULL,'Y','2017-02-16 10:56:59','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('000010003','删除','修改','00001',NULL,'Y','2017-02-16 10:55:05','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('000010004','添加','添加','00001',NULL,'Y','2017-02-16 10:55:14','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('000010005','审核','审核','00001',NULL,'Y','2017-02-16 10:55:20','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('000010006','打印','打印','00001',NULL,'Y','2017-02-16 10:55:26','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('000010007','导出','导出','00001',NULL,'Y','2017-02-16 10:55:32','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('000010008','导入','导入','00001',NULL,'Y','2017-02-16 10:55:36','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('000010009','下载','下载','00001',NULL,'Y','2017-02-16 10:55:43','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('000010010','上传','上传','00001',NULL,'Y','2017-02-16 10:55:50','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*Table structure for table `sys_dictionary_type_info` */

DROP TABLE IF EXISTS `sys_dictionary_type_info`;

CREATE TABLE `sys_dictionary_type_info` (
  `DICTIONARY_TYPE_ID` varchar(10) NOT NULL COMMENT '字典主键',
  `DICTIONARY_TYPE_NAME` varchar(10) NOT NULL COMMENT '字典名称',
  `DICTIONARY_TYPE_DESC` varchar(100) NOT NULL COMMENT '字典内容描述',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT 'Y' COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  PRIMARY KEY (`DICTIONARY_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `sys_dictionary_type_info` */

insert  into `sys_dictionary_type_info`(`DICTIONARY_TYPE_ID`,`DICTIONARY_TYPE_NAME`,`DICTIONARY_TYPE_DESC`,`REMARK`,`STATUS`,`CREATE_TIME`,`CREATE_USER_ID`,`CREATE_USER_NAME`,`CREATE_TEAM_ID`,`CREATE_TEAM_NAME`,`CREATE_DEPART_ID`,`CREATE_DEPART_NAME`,`CREATE_UNIT_ID`,`CREATE_UNIT_NAME`,`LAST_UPDATE_TIME`,`LAST_UPDATE_USER_ID`,`LAST_UPDATE_USER_NAME`,`LAST_UPDATE_TEAM_ID`,`LAST_UPDATE_TEAM_NAME`,`LAST_UPDATE_DEPART_ID`,`LAST_UPDATE_DEPART_NAME`,`LAST_UPDATE_UNIT_ID`,`LAST_UPDATE_UNIT_NAME`) values ('00001','操作按钮','功能模块操作按钮',NULL,'Y','2017-02-16 10:53:52','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','系统管理员',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*Table structure for table `sys_function_info` */

DROP TABLE IF EXISTS `sys_function_info`;

CREATE TABLE `sys_function_info` (
  `FUNCTION_ID` varchar(100) NOT NULL COMMENT '主键',
  `FUNCTION_NAME` varchar(10) NOT NULL COMMENT '菜单名称',
  `FUNCTION_DESC` varchar(100) NOT NULL COMMENT '菜单描述',
  `PARENT_FUNCTION_ID` varchar(10) NOT NULL COMMENT '父菜单编号',
  `FUNCTION_URL` varchar(1000) NOT NULL COMMENT '菜单链接地址',
  `FUNCTION_SEQUE` varchar(100) NOT NULL COMMENT '菜单顺序',
  `IS_VIRTUAL` varchar(10) NOT NULL COMMENT '是否虚节点（0：虚节点，1：实节点）',
  `FUNCTION_TYPE` varchar(10) NOT NULL COMMENT '菜单类型（1、功能；2、操作按钮）',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT 'Y' COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `DICTIONARY_ID` varchar(100) DEFAULT NULL COMMENT '字典内容主键(SYS_DICTIONARY_INFO.DICTIONARY_ID)',
  `DICTIONARY_NAME` varchar(100) DEFAULT NULL COMMENT '字典内容名称(SYS_DICTIONARY_INFO.DICTIONARY_NAME)',
  PRIMARY KEY (`FUNCTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `sys_function_info` */

insert  into `sys_function_info`(`FUNCTION_ID`,`FUNCTION_NAME`,`FUNCTION_DESC`,`PARENT_FUNCTION_ID`,`FUNCTION_URL`,`FUNCTION_SEQUE`,`IS_VIRTUAL`,`FUNCTION_TYPE`,`REMARK`,`STATUS`,`CREATE_TIME`,`CREATE_USER_ID`,`CREATE_USER_NAME`,`CREATE_TEAM_ID`,`CREATE_TEAM_NAME`,`CREATE_DEPART_ID`,`CREATE_DEPART_NAME`,`CREATE_UNIT_ID`,`CREATE_UNIT_NAME`,`LAST_UPDATE_TIME`,`LAST_UPDATE_USER_ID`,`LAST_UPDATE_USER_NAME`,`LAST_UPDATE_TEAM_ID`,`LAST_UPDATE_TEAM_NAME`,`LAST_UPDATE_DEPART_ID`,`LAST_UPDATE_DEPART_NAME`,`LAST_UPDATE_UNIT_ID`,`LAST_UPDATE_UNIT_NAME`,`DICTIONARY_ID`,`DICTIONARY_NAME`) values ('001','十达模板管理系统','十达模板管理系统','-1','/','1','1','1',NULL,'Y','2017-02-15 22:09:00','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('001001','系统管理','系统管理','001','/sysManage','1','0','1',NULL,'Y','2017-02-15 22:14:35','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('001001001','组织架构','组织架构','001001','sysManage/sysUnitInfo/index.html','1','0','1',NULL,'Y','2017-02-15 22:15:57','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('001001002','用户管理','用户管理','001001','sysManage/sysUserInfo/index.html','2','0','1',NULL,'Y','2017-02-15 22:17:00','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('001001003','功能菜单','功能菜单','001001','sysManage/sysFunctionInfo/sysFunctionInfo.html','3','0','1',NULL,'Y','2017-02-15 22:18:42','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('001001004','角色管理','角色管理','001001','sysManage/sysRoleInfo/sysRoleInfo.html','1','0','1',NULL,'Y','2017-02-16 13:26:43','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'',''),('001001004001','查询','角色管理','001001004','sysManage/sysRoleInfo/sysRoleInfo.html','1','0','2',NULL,'Y','2017-02-16 13:26:43','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'000010001','查询'),('001001004002','修改','角色管理','001001004','sysManage/sysRoleInfo/sysRoleInfo.html','1','0','2',NULL,'Y','2017-02-16 13:26:43','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'000010002','修改'),('001001005','审批管理','审批管理','001001','sysManage/approven/index.html','1','0','1',NULL,'Y','2017-02-16 14:42:58','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'',''),('001001005001','查询','审批管理','001001005','sysManage/approven/index.html','1','0','2',NULL,'Y','2017-02-16 14:42:58','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'000010001','查询'),('001001005002','修改','审批管理','001001005','sysManage/approven/index.html','1','0','2',NULL,'Y','2017-02-16 14:42:58','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'000010002','修改'),('001002','测试','测试','001','','1','0','1',NULL,'Y','2017-02-16 13:27:00','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'',''),('001002001','测试1','cc ','001002','/','1','0','1',NULL,'Y','2017-02-16 14:28:45','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'',''),('001002001001','查询','cc ','001002001','/','1','0','2',NULL,'Y','2017-02-16 14:28:45','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'000010001','查询'),('001002001002','修改','cc ','001002001','/','1','0','2',NULL,'Y','2017-02-16 14:28:45','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'000010002','修改');

/*Table structure for table `sys_log_info` */

DROP TABLE IF EXISTS `sys_log_info`;

CREATE TABLE `sys_log_info` (
  `LOG_ID` varchar(10) NOT NULL COMMENT '主键',
  `OPERATE_PERSON_ID` varchar(10) NOT NULL COMMENT '菜单名称',
  `OPERATE_PERSON_NAME` varchar(100) NOT NULL COMMENT '菜单描述',
  `OPERATE_TIME` varchar(10) NOT NULL COMMENT '父菜单编号',
  `FUNCTION_URL` varchar(10) NOT NULL COMMENT '菜单链接地址',
  `FUNCTION_NAME` varchar(100) NOT NULL COMMENT '菜单顺序',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT 'Y' COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `sys_log_info` */

/*Table structure for table `sys_role_info` */

DROP TABLE IF EXISTS `sys_role_info`;

CREATE TABLE `sys_role_info` (
  `ROLE_ID` varchar(100) NOT NULL COMMENT '主键',
  `ROLE_NAME` varchar(10) NOT NULL COMMENT '角色名',
  `ROLE_DESC` varchar(100) NOT NULL COMMENT '角色描述',
  `FUNCTION_IDS` varchar(1000) NOT NULL COMMENT '功能编号',
  `FUNCTION_OPERATE_IDS` varchar(1000) DEFAULT NULL COMMENT '功能操作按钮菜单编号',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT 'Y' COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `sys_role_info` */

insert  into `sys_role_info`(`ROLE_ID`,`ROLE_NAME`,`ROLE_DESC`,`FUNCTION_IDS`,`FUNCTION_OPERATE_IDS`,`REMARK`,`STATUS`,`CREATE_TIME`,`CREATE_USER_ID`,`CREATE_USER_NAME`,`CREATE_TEAM_ID`,`CREATE_TEAM_NAME`,`CREATE_DEPART_ID`,`CREATE_DEPART_NAME`,`CREATE_UNIT_ID`,`CREATE_UNIT_NAME`,`LAST_UPDATE_TIME`,`LAST_UPDATE_USER_ID`,`LAST_UPDATE_USER_NAME`,`LAST_UPDATE_TEAM_ID`,`LAST_UPDATE_TEAM_NAME`,`LAST_UPDATE_DEPART_ID`,`LAST_UPDATE_DEPART_NAME`,`LAST_UPDATE_UNIT_ID`,`LAST_UPDATE_UNIT_NAME`) values ('001001001002001','系统管理员','角色',',001001001,001001002,001001003,001001004,001001005,,001002001,',',001001004001,001001004002,',NULL,'Y','2017-02-16 14:26:51','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('001002001','管理员','管理员',',001001001,001001002,001001003,001001004,001001006,001001007,001001008,001002001,001002002,001004001,001004002,P001001001,',NULL,NULL,NULL,'2017-02-15 22:20:35','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*Table structure for table `sys_unit_info` */

DROP TABLE IF EXISTS `sys_unit_info`;

CREATE TABLE `sys_unit_info` (
  `UNIT_ID` varchar(10) NOT NULL COMMENT '单位编号',
  `UNIT_NAME` varchar(10) NOT NULL COMMENT '单位名称',
  `FUNCTION_SEQUE` varchar(100) NOT NULL COMMENT '顺序',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT 'Y' COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  PRIMARY KEY (`UNIT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `sys_unit_info` */

/*Table structure for table `sys_user_info` */

DROP TABLE IF EXISTS `sys_user_info`;

CREATE TABLE `sys_user_info` (
  `USER_ID` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '单位编号',
  `EMPLOYEE_ID` varchar(100) DEFAULT NULL COMMENT '员工id主键',
  `USER_NAME` varchar(100) NOT NULL COMMENT '用户名',
  `LOGIN_NAME` varchar(100) NOT NULL COMMENT '系统登录名(登录用户名)',
  `LOGIN_PWD` varchar(100) NOT NULL COMMENT '系统登录密码',
  `TEAM_ID` varchar(100) DEFAULT NULL COMMENT '所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `DEPART_ID` varchar(100) DEFAULT NULL COMMENT '所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `UNIT_ID` varchar(100) NOT NULL COMMENT '主键',
  `UNIT_NAME` varchar(100) NOT NULL COMMENT '组织名称',
  `USER_NO` varchar(100) DEFAULT NULL COMMENT '用户编号',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT 'Y' COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `UK_sys_user_info` (`LOGIN_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

/*Data for the table `sys_user_info` */

insert  into `sys_user_info`(`USER_ID`,`EMPLOYEE_ID`,`USER_NAME`,`LOGIN_NAME`,`LOGIN_PWD`,`TEAM_ID`,`TEAM_NAME`,`DEPART_ID`,`DEPART_NAME`,`UNIT_ID`,`UNIT_NAME`,`USER_NO`,`REMARK`,`STATUS`,`CREATE_TIME`,`CREATE_USER_ID`,`CREATE_USER_NAME`,`CREATE_TEAM_ID`,`CREATE_TEAM_NAME`,`CREATE_DEPART_ID`,`CREATE_DEPART_NAME`,`CREATE_UNIT_ID`,`CREATE_UNIT_NAME`,`LAST_UPDATE_TIME`,`LAST_UPDATE_USER_ID`,`LAST_UPDATE_USER_NAME`,`LAST_UPDATE_TEAM_ID`,`LAST_UPDATE_TEAM_NAME`,`LAST_UPDATE_DEPART_ID`,`LAST_UPDATE_DEPART_NAME`,`LAST_UPDATE_UNIT_ID`,`LAST_UPDATE_UNIT_NAME`) values (0000000001,'0000000001','系统管理员','admin','670b14728ad9902aecba32e22fa4f6bd','','','','','001','集团',NULL,NULL,'Y','2017-02-15 22:36:34','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001','2017-02-16 14:46:45','0000000001','系统管理员','','','','','001','集团'),(0000000002,NULL,'杨洋','yangyang','670b14728ad9902aecba32e22fa4f6bd','','','','','001001001','十达科技',NULL,NULL,'Y','2017-02-16 14:48:29','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*Table structure for table `sys_user_role` */

DROP TABLE IF EXISTS `sys_user_role`;

CREATE TABLE `sys_user_role` (
  `USER_ID` varchar(10) NOT NULL COMMENT '用户id',
  `ROLE_ID` varchar(100) NOT NULL COMMENT '角色id',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(100) DEFAULT 'Y' COMMENT '状态（Y正常,N禁用）',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(100) NOT NULL COMMENT '创建人编号(SYS_USER_INFO.USER_ID)',
  `CREATE_USER_NAME` varchar(100) NOT NULL COMMENT '创建人姓名(SYS_USER_INFO.USER_NAME)',
  `CREATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '创建人所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '创建人所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `CREATE_UNIT_ID` varchar(100) NOT NULL COMMENT '创建人所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `CREATE_UNIT_NAME` varchar(100) NOT NULL COMMENT '创建人所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `LAST_UPDATE_USER_ID` varchar(100) DEFAULT NULL COMMENT '最后更新人编号(SYS_USER_INFO.USER_ID)',
  `LAST_UPDATE_USER_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新人姓名(SYS_USER_INFO.USER_NAME)',
  `LAST_UPDATE_TEAM_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_TEAM_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属班组名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_DEPART_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_DEPART_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属科室名称(SYS_DEPART_INFO.DEPART_NAME)',
  `LAST_UPDATE_UNIT_ID` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位编号(SYS_DEPART_INFO.DEPART_ID)',
  `LAST_UPDATE_UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '最后更新所属单位名称(SYS_DEPART_INFO.DEPART_NAME)',
  UNIQUE KEY `UK_sys_user_role` (`USER_ID`,`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `sys_user_role` */

insert  into `sys_user_role`(`USER_ID`,`ROLE_ID`,`REMARK`,`STATUS`,`CREATE_TIME`,`CREATE_USER_ID`,`CREATE_USER_NAME`,`CREATE_TEAM_ID`,`CREATE_TEAM_NAME`,`CREATE_DEPART_ID`,`CREATE_DEPART_NAME`,`CREATE_UNIT_ID`,`CREATE_UNIT_NAME`,`LAST_UPDATE_TIME`,`LAST_UPDATE_USER_ID`,`LAST_UPDATE_USER_NAME`,`LAST_UPDATE_TEAM_ID`,`LAST_UPDATE_TEAM_NAME`,`LAST_UPDATE_DEPART_ID`,`LAST_UPDATE_DEPART_NAME`,`LAST_UPDATE_UNIT_ID`,`LAST_UPDATE_UNIT_NAME`) values ('0000000001','001001001002001',NULL,'Y','2017-02-16 14:52:59','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('0000000001','001002001',NULL,'Y','2017-02-15 22:37:21','0000000001','系统管理员',NULL,NULL,NULL,NULL,'001','001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('0000000002','001001001002001',NULL,'Y','2017-02-16 14:50:50','0000000001','系统管理员','','','','','001','集团',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
